### ISSUE TITLE
Drive to last position before first motor movement

### ISSUE THREAD

**Issue by ubmarco** [AlexBischof/BabySnoozer#2]
Servos do not have position control feedback. The Tinkerforge (TF) SW has to assume the servo can follow the PWM control signal. After power-up, the TF servo brick firmware has no idea where the servo is because there was no target angle movement yet. So the initial angle is set to 0.
If first movement is done using a velocity and acceleration below 65535, the servo brick firmware will transit from position 0 to the target position with the defined velocity and acceleration. Now if the servo is not at position 0 at the beginning (which is commonly the case), it will turn with max speed to 0 first and then follow the PWM movement.

This can be resolved by overwriting the init position in the firmware with the current position. This can be achieved by setting the current servo position with full speed and acceleration. This has to be done directly before the first servo movement, either in learn process or during normal BabySnooze phase. It should be done at a time where the user expects a movement anyway. So don't start up the software and directly set the current position.

The last position is stored in a special file after each servo movement. The idea is to be sure to always capture the last position, even if the user does an instant power shutdown after a servo run.

See also the discussion in http://www.tinkerunity.org/forum/index.php/topic,2912.0.html

**Comment by AlexBischof** [comment]
Implemented a FullSpeedLastExecutor which handles the process. Still open is the "always capture" functionality
